### ISSUE TITLE
Check if bug fix in SQ VTK visualization is needed

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/superquadric-lib#24]
More information are available [here](https://github.com/robotology/find-superquadric/pull/3#issuecomment-479570116).

**Comment by xEnVrE** [comment]
Hi @giuliavezzani,

by chance I was comparing a superquadric and a point cloud sampled over the superquadric and I found that the bug is also affecting library `SuperquadricVis`.

I'm attaching two examples for a superquadric with parameters:
- position = 0
- orientation = 0
- a1, a2, a3 = [0.8, 0.9, 2.0]
- e1, e2 = [0.1, 1.0]

Actual implementation of class `SuperqVis::Visualizer`:
![bad_sq](https://user-images.githubusercontent.com/6014499/55684245-4f558480-5949-11e9-8eef-5bd328e43f36.png)

After changes similar to those applied in [this](https://github.com/robotology/find-superquadric/pull/3) PR:
![good_sq](https://user-images.githubusercontent.com/6014499/55684244-4ebcee00-5949-11e9-9843-46494bbb7e6d.png)

**Comment by giuliavezzani** [comment]
Thanks @xEnVrE! I was planning to test it after the defence 😉 
If you want to modify the library with a pull request you are welcome 😃

**Comment by xEnVrE** [comment]
Sure :smile:
